print ("****************************************************************************")
print ("***************** Program Menghitung Nilai Tugas ***************************")
print ("****************************************************************************")
print ("")
print ("Nilai Total Tugas adalah (Nilai Tugas 1 + Nilai Tugas 2 + Nilai Tugas 3) Dibagi)3")
print ()
nama =input("\tmasukan nama mahasiswa: ")
nim = input("\tmasukan NIM Mahasiswa: ")
matkul = input("\tmasukan Mata Kuliah: ")
tugas_1 = float(input("\tmasukan Nilai Tugas 1: "))
tugas_2 = float(input("\tmasukan Nilai Tugas 2: "))
tugas_3 = float(input("\ttmasukan Nilai Tugas 3: "))
print ()
nilai = (tugas_1 + tugas_2 + tugas_3)/3
print ("-------------------------------------------------------------------------------")
print ("")
print ("Nilai tugas")
print ("Nama Mahasiswa :",nama)
print ("masukan NIM Mahasiswa:",nim)
print ("masukan Mata Kuliah:",matkul)
print ("nilai :",nilai)
print ("Nilai dibulatkan menjadi:",round(nilai))
